### ISSUE TITLE
Plugin does not work on backgroud, the trigger not working until I open Home app - after that trigger start,

### ISSUE THREAD

**Issue by CharlieVD** [zerwuff/homebridge-alphaess#12]
**Describe The Bug:**

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
Please enable Debug Mode (-D)  in Homebridge to see more details about the homebridge-alphaess plugin  
Show the Homebridge logs here, remove any sensitive information.

```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by zerwuff** [comment]
Please provide more details so i can work on a fix.
Logs, Screenshots of Trigger Image - what trigger exactly ? 
Thanks

**Comment by CharlieVD** [comment]
Hi,

 

Thanks for prompt answer.

 

Installation:

*	NAS Synology server + Homebridge
*	Your plug-in 
*	Added to Apple Home

 

I can see % of battery, solar power and contact sensor.

 

I set trigger to 1500W and 80% and some automation on it. When solar reaches these values, nothing happened. 

I must open Apple Home app or Eve app – after that contact opens, and automation start.

 

Thanks for help, Your plugin is very useful.

 

Best regards

 

Karel

**Comment by CharlieVD** [comment]
Also sending log.

 

[4/21/2024, 11:52:20 AM] [Alpha ESS Homebridge Plugin] Restarting Process...

[4/21/2024, 11:52:21 AM] [Alpha ESS Homebridge Plugin] Launched child bridge with PID 1975

[4/21/2024, 11:52:22 AM] Registering platform 'homebridge-alphaess.AlphaEssPlatform'

[4/21/2024, 11:52:22 AM] [Alpha ESS Homebridge Plugin] Loaded homebridge-alphaess v2.95.0 child bridge successfully

[4/21/2024, 11:52:22 AM] Loaded 0 cached accessories from cachedAccessories.0E96CB6D12D3.

[4/21/2024, 11:52:22 AM] [Alpha ESS Homebridge Plugin] Alpha Ess Platform Plugin started 

[4/21/2024, 11:52:23 AM] Initializing platform accessory 'AlphaEssBatteryLightLevel'...

[4/21/2024, 11:52:23 AM] Initializing platform accessory 'AlphaEssBatteryHumidity'...

[4/21/2024, 11:52:23 AM] Initializing platform accessory 'EnergyTriggerPlugin'...

[4/21/2024, 11:52:23 AM] Homebridge v1.8.0 (HAP v0.12.0) (Alpha ESS Homebridge Plugin) is running on port 59372.

Fontconfig error: Cannot load default config file: No such file: (null)

**Comment by CharlieVD** [comment]
I just enabled debug mode on Homebridge and got other info

 

[4/21/2024, 11:55:58 AM] [homebridge-alphaess] This plugin generated a warning from the characteristic 'Current Ambient Light Level': characteristic was supplied illegal value: number 0 exceeded minimum of 0.0001. See https://homebridge.io/w/JtMGR for more info.

[4/21/2024, 11:55:58 AM] [homebridge-alphaess] Error: 

    at CurrentAmbientLightLevel.Characteristic.characteristicWarning (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)

    at CurrentAmbientLightLevel.Characteristic.validateUserInput (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2923:14)

    at CurrentAmbientLightLevel.<anonymous> (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2405:24)

    at step (/volume1/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)

    at Object.next (/volume1/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)

    at fulfilled (/volume1/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:166:62)

    at processTicksAndRejections (node:internal/process/task_queues:95:5)

[4/21/2024, 11:55:58 AM] [homebridge-landroid] Create folder activityLog and set states.

[4/21/2024, 11:55:58 AM] [Alpha ESS Homebridge Plugin] SOC: 100

[4/21/2024, 11:55:58 AM] [Alpha ESS Homebridge Plugin] SOC: 100

[4/21/2024, 11:55:58 AM] [Alpha ESS Homebridge Plugin] SOC: 100

[4/21/2024, 11:55:58 AM] [Alpha ESS Homebridge Plugin] soc: 100

[4/21/2024, 11:55:58 AM] [Alpha ESS Homebridge Plugin] pBatt :451

[4/21/2024, 11:55:58 AM] [Alpha ESS Homebridge Plugin] stringPowerTotal :1778

[4/21/2024, 11:55:58 AM] [Alpha ESS Homebridge Plugin] Power total on the strings :1778 is over threshold:1500 power trigger: true

[4/21/2024, 11:55:58 AM] [Alpha ESS Homebridge Plugin] Battery SOC:100 is over threshold:80 soc trigger:true 

[4/21/2024, 11:55:58 AM] [Alpha ESS Homebridge Plugin] Calculating trigger ->  powerLoadingThreshold: 1500 socLoadingThreshold:80 resulting in trigger:true

**Comment by zerwuff** [comment]
Hi please Check the latest Version, this will Update the Status directly.

**Comment by CharlieVD** [comment]
Thanks, 

I updated it, but it does not update status in Apple Homekit. I must open Home app to get notification.

**Comment by zerwuff** [comment]
Hi Karel, thanks for checking out. 
Is the issue that **you don't get any** notification about the trigger at all in the home app ? **or is it just delayed** ? 
Maybe do the following: check the console when the trigger is fired - scan the log for "resulting in trigger:true" , then the
plugin calculated its internal state of the trigger to true (done every 5mins or so, as you configured the scan interval).
then wait and see if you receive any trigger at all in the home app.  

I use the trigger by myself, but only via the mqtt (since this matches my infrastructure) - there its working fine, trigger fired instatly. I will test this on myself with the home app. I haven't really tested this a lot-

Can you also check:  https://github.com/nitaybz/homebridge-delay-switch  and test a timed automation ? after a fixed time, it should trigger your automation. does this work? 
maybe its an issue with homebridge installation and your home app, just to exclude this in the possbile problems.
internally, the timed based plugins does the same calls as i do in the alpha ess homebridge plugin.

**Comment by CharlieVD** [comment]
Hi,

 

Thanks for kind help, very appreciate it. 

 

I don ‘t get any notification. I must open app. 

 

My settings in Homebridge are:

{

            "name": "Alpha ESS Homebridge Plugin",

            "alphaUrl": https://openapi.alphaess.com/api,

            "appid": "alphaxxxxxxxxxxxxxxxxxxx",

            "appsecret": "xxxxxxxxxxxxx",

            "serialnumber": "ALBxxxxxxxxxxxxxxx",

            "powerLoadingThreshold": 3000,

            "socLoadingThreshold": 80,

            "refreshTimerInterval": 100000,

            "power_image_filename": "/tmp/alpha_power_image.png",

            "logrequestdata": true,

            "tibberEnabled": false,

            "tibberLoadBatteryEnabled": false,

            "tibberLoadingMinutes": 60,

            "tibberThresholdSOC": 60,

            "tibberThresholdEur": 0.01,

            "triggerImageFilename": "/tmp/tibber_image.png",

            "_bridge": {

                "username": "0E:96:CB:6D:12:D3",

                "port": 59372

            },

            "platform": "AlphaEssPlatform"

        }

 

 

I also tested homebridge delay switch configured as door sensor and it works perfectly.  I got immediately notification in AppleHome.

 

 

Enclosed I am sending log file. 

 

Best regards

 

 

Karel

**Comment by zerwuff** [comment]
Should be fixed now in the latest Version for both trigger and lumination value. Could you verify this and close the issue if also working for you ? BR

**Comment by CharlieVD** [comment]
Hi,

 

I tested new plugin a lot directly in browser on Homebridge page to be sure, that it is correct. I set power to 4000 W (lux) a refresh time to 1 minute – 60000.

I am not sure about value “socLoadingThreshold” – what exactly do. Will You explain me this?

 

In browse every 1 minute updated value of lamination BUT not value of contact. For example value of lamination was 4500 and contact keep closed. When I refresh page in browser, contact was open and I got notification from AppleHome.

After 1 minute value of lamination was updated on contact ALWAYS was closed even if value of lamination was higher then 4000. After refresh of page again open and again closed after 1 minute.

 

It also happened when I open AppleHome app (it is like refresh page in browser) – contact is open (if value is over 4000) and after 1 minute again closed.

 

 

Can I ask You to change values for automation – lamination. The range now is 5-20…to max. 6000. But my FVE can give up to 10000 and some times more. My opinion is the best is to have possibility set range after 1000 to 11000. For me is very important to know, if FVE produce more than 10000 to switch on some electric device.  

 

Best regards

 

Karel

**Comment by CharlieVD** [comment]
I would like to ask You, if is possible to trigger contact in some specific condition. It would be very welcome for owners of FVE.

 

What we need is to have possibility to trigger contact when solar power is over some value, but also battery has for example more that 80%. Also possibility to set time, how long must be solar power over set value to open contact, and under set value to close contact.

 

For example:

- open contact when power is over 4000 for 5 minutes and battery has mere that 80%

- close contact if power is less than 4000 for 10 minutes or battery level is les than 80%

 

If You can do it, Your plugnin will be perfect 😊

**Comment by zerwuff** [comment]
Hi the trigger is working as following :
 
If *socLoadingThreshold* (the soc threshold to enable the trigger, eg. 80 for 80%) and *powerLoadingThreshold* (the power threshold to enable the trigger. eg 2200 for 2200 watts) are met by the alpha ess values, the trigger is fired and the accessory will notify this to the home app as open circuit like and will be shown in the homebridge ui as:
    <img width="196" alt="open" src="https://github.com/zerwuff/homebridge-alphaess/assets/120713107/509fdf03-6817-40f6-a42f-4fb313509a28">

If the above conditions (either watts or soc threshold) from the alpha ess are below your configuration, the trigger will be notifying a closed circuit to the home app and a closed icon in the homebridge ui.
This works for the automation right now i guess and was broken before (needed to open the home app).

The lux value also provided is **not taken into account for the combined trigger** and will just report the value to the home app. you can set up automations on this on the home app.

I suggest the following -> if the combined trigger works now as expected please close the bug.

The ideas 
```
- open contact when power is over 4000 for 5 minutes and battery has mere that 80%
- close contact if power is less than 4000 for 10 minutes or battery level is les than 80%
```
are a new feature request https://github.com/zerwuff/homebridge-alphaess/issues/13 

Ok with you ?

**Comment by CharlieVD** [comment]
Thank You for an answer.

 

I am not sure I can understand exactly. 

 

Let's explain it on example:

 

Plugin is set to:

socLoadingThreshold : 100 %

powerLoadingThreshold : 4000

 

Contact should be OPEN if BOTH values are more than set values? If one of
them is lower, contact should be closed?

 

If YES, it does not work properly. I have whole day battery on 100% and
power was very often more than 4000, BUT contact was closed (until refresh)
and on next refresh was again CLOSED.

I do not think, that it works properly.

 

 

Good message is, that automation based on lamination works properly.  Main
problem is that is not possible to set more detailed values (max and steps)
to be usable. Can You change it?

Only small detail - when power is for example 4500 and I set automation
point for example 4000 to trigger automation, it does not work on next
update. You must wait until power is less then 4000 and after power is again
higher than  4000 it starts work.

 

I will also try automation based on battery level - I have to wait - it is
still 100%.

 

Best regards

 

 

Karel

**Comment by CharlieVD** [comment]
Hi,

I tested battery in automation, and it also does not work in background. You must open app to start automation.

Lumination(power) works well.

**Comment by zerwuff** [comment]
It works as intended, regarding to your comments:

lets explain :) 
your config:
socLoadingThreshold : 100 (trigger >=100% soc of battery)
powerLoadingThreshold : 4000 (trigger =>4000 watts of solar power)

create an home automation: 
eg: play music from homepod when alpha ess trigger sensor gets **opened**

the thing is, the home app needs to regognize that switchover between below -> above threshold to open the circuit.
**time:**
10.00 o clock: soc 80%, power 4200 watts -> trigger closed
11.00 o clock: soc 90%, power 4600 watts -> trigger closed 
12.00 o clock: soc 100%, power 5000 watts -> both conditions met. homebridge opens the trigger and sends it to the home app. **only then** automation gets started because the trigger **switchover from close->open was detected**. only here starts the automation !  i.e. the automation remembers the state before and triggers **only** if the state **changes**.

from the plugin perspective, this works as intended. i tested the above scenario and started the automation thereover.

battery level update was fixed in 2.99 please update.

**Comment by CharlieVD** [comment]
Hi again,

 

Appreciate time You spent with it. From Your explanation I understood, the it should work as I think.

 

If both conditions are met, the trigger should OPEN contact and run automation You set.

 

Be sure, that I spend a lot of time to test it in different automations, but it works this way ONLY when I open any app which refresh status. Its open (all automations starts) and after 1 minute close itself even both conditions are still met. Never in background. It is my real experience on real AlphaEss. 

 

On background works automation based on lumination and believe on battery in future. In this case it can be used instead of contact. 

I only ask You do change range and step for settings power. Will You change it?

 

Your plugin is very useful and has big potential to future. I want to help only.

 

Regards

**Comment by zerwuff** [comment]
hi, i did some more improvements to reduce flakyness of the trigger, still working on it 
 
`I only ask You do change range and step for settings power. Will You change it?
`
do you mean within the home app ? this comes from apple, i cannot change this :( 
please give me your feedback, thanks

**Comment by CharlieVD** [comment]
https://github.com/zerwuff/homebridge-alphaess/assets/167674230/12b63026-8d28-4f40-8464-f67cf6366bd0

Hi,

I am testing Your plugin. Unfortunately, it does not work as it should. Enclosed I am sending video from mobile where You can see it. 
It open when I refresh page and after that closed without any reason.

I also testing automations based on solar power and battery level. I will let You know..

Best regards

Karel

**Comment by zerwuff** [comment]
Hi Karol thanks for the Video. I am Curios what the log Shows in this time could you make one again and attach the log of the time? So i See what the Plugin is doing. Is the trigger Working now on the background - starting automations without opening the Home App ?

**Comment by CharlieVD** [comment]
Hi,

 

Enclosed sending log file. Trigger is not working on background without opening apps. 

 

Good message is, that solar power and battery level are working on background and can be used instead of contact trigger. You must set 2 params in automation. It is not possible in Apple Home app, but I use EVE app, where it is possible. There is also possible set solar power as I need. Just testing different situations.

 

Can I ask You about other thing? I AlphaESS app I can see other params like “Feed-in”, ”Load”. Can You add it to plugin, or it is not possible?

 

Best regards and thank You.

 

Karel

**Comment by zerwuff** [comment]
Hi Karol, thanks for providing the log. I saw that your contact went from CONTACT_NOT_DETECTED around 5:38:05 to -> CONTACT_DETECTED around 5:44:05, because the plugin "thought" that the trigger situation was not met  (log message: "Calculated triggers: alpa ess: false tibber: false triggerTotal :false" ) around 5:44:05 PM.

I just identified a bug that came up when Alpha delivered bad values and this could be the reason of your log. i made it more robust (take the last values if alpha ess api is broke) -  should be more stable in total now.
if the plugin asks the alpha ess API too often, they will respond with "try again later, your requests are too often". 
i would suggest to increment the interval - 5 min instead of min. 

in the home app:
your automation should look like  "if alpha ess trigger **open**,  start automation".  open means reaching the trigger values (high energy, battery full), close means the opposite. is this the case ?
i have set it so on my side with working trigger on/off. 

please try the latest version and provide video + log from this time so i can check the log. thanks for your feedback. 
the new values can be implemented. please log a feature request ticket so i can look after it. lets not mix up too much in one ticket :) 
BR

**Comment by CharlieVD** [comment]
Hi again,

 

I tested a lot a have good message. 

 

This plugin :

*	Finally works on background
*	keep contact OPEN – if conditions are met

 

What is not perfect is, that OPEN/CLOSE contact is with quite big delay – up to 1 minute..

 

I tested it two ways:

*	set plugin to 4000/90
*	created automation based on lamination/humidity at the same values 4000/90

 

While automation was always trigged immediately, contact was trigged with big delay.

 

It is last thing, that should be solved.

 

Thanks for good work 😊

 

Regards

 

Karel

**Comment by zerwuff** [comment]
Hi Karol, all data events should be on time sync now. please check latest build version.  thanks!

**Comment by CharlieVD** [comment]
Hi,

 

Just quick reaction, contact reacts immediately, it is perfect.

 

BUT, after restart of plugin/bridge initial values are 1 lux a 0% of battery until next synchro – several minutes. It starts wrong automations. Can You repair it?

 

Regards

 

K.

**Comment by CharlieVD** [comment]
You added other value “Load” ?

**Comment by zerwuff** [comment]
the 1 > 0 value thing is fixed - now. this should be all to fix for this bug now. if ok, close it.

fyi, i started already to add the load, which is a part from the feature request as preview. i update the feature ticket if its finished and ready to test.

**Comment by CharlieVD** [comment]
The problems is not fixed, after restart plugin all values 0 – till net synchro

**Comment by zerwuff** [comment]
that is fine, it is just the initial values, before having any data at all it is 0. after first sync (after 1 min in your case), the values shall be correct.

**Comment by zerwuff** [comment]
i just added a quick initial load after 10s for initial values.

**Comment by CharlieVD** [comment]
It works properly at the moment. Thanks
